version: '3.9'

name: topics-api
services:
  database:
    image: postgres:17beta3-alpine3.20
    ports:
      - "5433:5432"
    volumes:
      - ~/workspace/topics/volumes:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=topics