/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-gradle-plugin:3.3.2")
    implementation("org.apache.commons:commons-text:1.12.0")

    implementation(project(":domain"))
    implementation(project(":adapter:web"))
    implementation(project(":adapter:jdbc"))
}

springBoot {
    mainClass = "com.example.app.App"
}
